<?php $_nico_settings  = array (
  'sliders' => 
  array (
    'Homepage' => 
    array (
      'active' => 'Elastic slider',
      'Elastic slider' => 
      array (
        'slideshow_interval' => '15000',
      ),
    ),
    'Product page' => 
    array (
      'active' => 'Cloud zoom',
    ),
  ),
  'options' => 
  array (
    0 => NULL,
    ' .image .description' => 
    array (
      'display' => 'block',
    ),
    ' div.image &gt; span.description ' => 
    array (
      'display' => 'block',
    ),
    '#social_band' => 
    array (
      'display' => 'block',
    ),
    '#language' => 
    array (
      'display' => 'none',
    ),
    '#currency' => 
    array (
      'display' => 'block',
    ),
    ' .product-grid .cart input.button, .box-product .cart input.button' => 
    array (
      'color' => '#cccccc',
    ),
    '#header #logo a span' => 
    array (
      'display' => 'inline',
    ),
    '#header #logo a img' => 
    array (
      'display' => 'none',
    ),
    '#menu' => 
    array (
      'border-top' => 'none',
      'border-bottom' => 'none',
    ),
    '#menu &gt; div &gt; ul &gt; li &gt; a' => 
    array (
      'padding' => '10px 15px',
    ),
    '#container' => 
    array (
      'margin' => '20px auto',
      'box-shadow' => 'none',
    ),
    '#carousel0' => 
    array (
      'color' => '#cccccc',
    ),
    '.product-info .description' => 
    array (
      'border-top' => '1px solid ',
    ),
    '.product-info .product_wish_compare' => 
    array (
      'display' => 'block',
    ),
    '.share' => 
    array (
      'display' => 'block',
    ),
    '#tab-description' => 
    array (
      'height' => 'auto',
    ),
    '#footer' => 
    array (
      'border-top' => '2px solid',
    ),
    '.column #phone' => 
    array (
      'display' => 'none',
    ),
    '#powered &gt; span' => 
    array (
      'display' => 'none',
    ),
    '.column #rss' => 
    array (
      'color' => '#cccccc',
    ),
  ),
  'fonts' => 
  array (
    0 => NULL,
    '#header #search input' => 
    array (
      'font-family' => '',
    ),
  ),
  'settings' => 
  array (
    0 => NULL,
    'phone_number' => '+123456789',
    'facebook' => 'sadasdsad',
    'twitter' => 'asdsad',
    'first_visit_message' => 'Hello, this site uses cookies!',
  ),
  'styles' => 
  array (
    0 => NULL,
    'primary_color' => 'catalog/view/theme/nicole-shop/nico_theme_editor/styles/primary_color-red_palette.css',
    'footer_color' => '',
    'secondary_color' => 'catalog/view/theme/nicole-shop/nico_theme_editor/styles/secondary_color-black_palette.css',
    'fonts' => 'catalog/view/theme/nicole-shop/nico_theme_editor/styles/fonts-lobster.css',
  ),
  'colors' => 
  array (
    '#header #search input' => 
    array (
      'color' => '#cccccc',
    ),
  ),
  'background-image' => 'url(http://www.activeaddict.co.uk/catalog/view/theme/nicole-shop/nico_theme_editor//patterns/foggy_birds.png)',
  'slider_text' => 
  array (
    0 => 
    array (
      'title' => 'Nicole Shop ',
      'subtitle' => 'Responsive Design',
      'description' => 'Responsive OpenCart Theme &amp; Modern Design
Compatible with versions 1.5.3 and 1.5.4 ',
    ),
    1 => 
    array (
      'title' => 'Nicole Shop',
      'subtitle' => 'Customization',
      'description' => 'Nicole Shop theme provides a panel at the bottom of the page that is visible only to users that have permission to modify layout/design',
    ),
    2 => 
    array (
      'title' => 'Nicole Shop',
      'subtitle' => 'Sliders',
      'description' => 'Nicole Shop it comes with 4 homepage sliders, Elastic Slider, Camera Slider, Flexislider and Nivo Slider',
    ),
  ),
);